title: Test site for themes
author: David LaMartina
email: david@davidlamartina.com
description: > # this means to ignore newlines until "baseurl:"
  Description - editable via _config.yml

# social links
twitter_username: your-twitter-handle
github_username:  DavidLaMartina

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
